intermediate

diff --git a/.github/workflows/build-bootc.yaml b/.github/workflows/build-bootc.yaml
--- a/.github/workflows/build-bootc.yaml
+++ b/.github/workflows/build-bootc.yaml
@@ -43,10 +43,12 @@ jobs:
       - name: Login to registry.redhat.io
         if: matrix.flavor == 'rhel'
         uses: docker/login-action@v3
+        id: rh-login
         with:
           registry: registry.redhat.io
           username: ${{ secrets.RH_REGISTRY_USERNAME }}
           password: ${{ secrets.RH_REGISTRY_PASSWORD }}
+        continue-on-error: true
 
       - name: Login to registry
         uses: docker/login-action@v3
@@ -54,7 +56,26 @@ jobs:
           registry: ${{ env.REGISTRY }}
           username: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}
           password: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_PASSWORD }}
+        continue-on-error: true
 
+      - name: Check login status
+        id: login-status
+        run: |
+          if [ ${{ steps.rh-login.outcome }} == "failure"]; then
+            if [
+              "${{ secrets.RH_REGISTRY_USERNAME }}" 
+              -a "${{ secrets.RH_REGISTRY_PASSWORD }}"
+              -a "${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}"
+              -a "${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_PASSWORD }}"
+            ]; then
+              exit 1
+            fi
+
+            echo "push_flag=false" >> "$GITHUB_OUTPUT"
+            exit 0
+          fi
+          echo "push_flag=true" >> "$GITHUB_OUTPUT"
+        
       - name: Build image
         id: build
         uses: docker/build-push-action@v5
@@ -77,5 +98,5 @@ jobs:
           context: bootc-agent-images/${{ matrix.flavor }}
           file: bootc-agent-images/${{ matrix.flavor }}/Containerfile
           platforms: linux/amd64,linux/arm64
-          push: true
+          push: ${{ fromJSON( steps.login-status.outputs.push_flag ) }}
           tags: ${{ env.REGISTRY }}/${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}/flightctl-agent-${{ matrix.flavor }}:bootstrap
